development:
  adapter: postgresql
  database: deblogsio_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: deblogsio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: deblogsio_production
  pool: 5
  timeout: 5000